# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "ehci_pci" "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];

  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7933e286-752a-4cc1-9a41-720bc45ee917";

    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  boot.initrd.luks.devices."luks".device =
    "/dev/disk/by-uuid/eae48266-7969-4fd9-95c4-ccdb5e691e3c";

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/7933e286-752a-4cc1-9a41-720bc45ee917";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/7933e286-752a-4cc1-9a41-720bc45ee917";
    fsType = "btrfs";
    options = [ "subvol=log" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6193-9278";
    fsType = "vfat";
  };

  fileSystems."/persist" =

    {
      device = "/dev/disk/by-uuid/7933e286-752a-4cc1-9a41-720bc45ee917";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/7933e286-752a-4cc1-9a41-720bc45ee917";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/263ade37-d777-4b57-8f46-5802c98ec89c"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
